{
  "jsonrpc": "2.0",
  "id": 123,
  "error": {
    "code": 200,
    "message": "Odoo Server Error",
    "data": {
      "name": "psycopg2.errors.DatatypeMismatch",
      "debug": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 2191, in __call__\n    response = request._serve_nodb()\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 1734, in _serve_nodb\n    response = self.dispatcher.dispatch(rule.endpoint, args)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 1998, in dispatch\n    result = endpoint(**self.request.params)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 722, in route_wrapper\n    result = endpoint(self, *args, **params_ok)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 155, in jsonrpc\n    return dispatch_rpc(service, method, args)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 388, in dispatch_rpc\n    return dispatch(method, params)\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 35, in dispatch\n    res = execute(db, uid, *params[3:])\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 65, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 50, in execute_cr\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 133, in retrying\n    result = func()\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 466, in call_kw\n    result = _call_kw_model_create(method, model, args, kwargs)\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 444, in _call_kw_model_create\n    result = method(recs, *args, **kwargs)\n  File \"<decorator-gen-282>\", line 2, in create\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 415, in _model_create_multi\n    return create(self, arg)\n  File \"/mnt/bck-addons/bi_appointment_management_system/models/appointment_type.py\", line 29, in create\n    res = super().create(vals_list)\n  File \"<decorator-gen-12>\", line 2, in create\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 415, in _model_create_multi\n    return create(self, arg)\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 4601, in create\n    records = self._create(data_list)\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 4789, in _create\n    cr.execute(SQL(\n  File \"/usr/lib/python3/dist-packages/odoo/sql_db.py\", line 332, in execute\n    res = self._obj.execute(query, params)\npsycopg2.errors.DatatypeMismatch: column \"company_id\" is of type integer but expression is of type integer[]\nLINE 1: ..., \"name\", \"write_date\", \"write_uid\") VALUES (1.0, ARRAY[1], ...\n                                                             ^\nHINT:  You will need to rewrite or cast the expression.\n\n",
      "message": "column \"company_id\" is of type integer but expression is of type integer[]\nLINE 1: ..., \"name\", \"write_date\", \"write_uid\") VALUES (1.0, ARRAY[1], ...\n                                                             ^\nHINT:  You will need to rewrite or cast the expression.\n",
      "arguments": [
        "column \"company_id\" is of type integer but expression is of type integer[]\nLINE 1: ..., \"name\", \"write_date\", \"write_uid\") VALUES (1.0, ARRAY[1], ...\n                                                             ^\nHINT:  You will need to rewrite or cast the expression.\n"
      ],
      "context": {}
    }
  }
}
